### PR TITLE
Added promote permission and fixed bskyblock.island.info description

### PR DESCRIPTION
**Pull request by YellowZaki**
I think bskyblock.island.info should be a mod command since it shows sensitive information like last login, uuid...

### CODE REVIEW

**Comment by tastybento** [comment]
@YellowZaki Is this actually a PR? I don't see any changes to the permission you mention. Should it be an issue?

**Comment by YellowZaki** [comment]
Look this https://github.com/BentoBoxWorld/BSkyBlock/pull/74/commits/c4ed0546228c992c4791faceaa195f32e7885a34

**Comment by smmmadden** [comment]
so is the description changing to: Let the player check other players info?
image
Based on the results, it looks like it gets player info for who enters the command.  The minecraft name and UUID are not considered sensitive.  It's public information that can be[ looked up by anyone:](https://mcuuid.net/) 
It's also only displaying that players info, not "other players info", so the description would still be incorrect in the PR.

**Comment by YellowZaki** [comment]
You can do /is info <player>
Last login is sensitive.

**Comment by smmmadden** [comment]
how is the last login of the current player sensitive?  If this command allows players to check info of other players, then we should not show the last login and the bottom portion (Island location, etc.)  That part would make sense.

**Pull request merged**
