### PR TITLE
Created Dutch (Nederlands) Local File

### PR DESCRIPTION
**Pull request by DarkVillager**

### CODE REVIEW

**Review by tastybento — CHANGES_REQUESTED** [review]
The name of the file needs to be nl.yml. Please update.

**Review by tastybento — APPROVED** [review]

**Comment by tastybento** [comment]
Thanks!

**Comment by tastybento** [comment]
If you get a chance, please review and correct the main NL file: https://gitlocalize.com/repo/2855/nl/src/main/resources/locales/en-US.yml

**Comment by DarkVillager** [comment]
> If you get a chance, please review and correct the main NL file: https://gitlocalize.com/repo/2855/nl/src/main/resources/locales/en-US.yml

I'll do that tomorrow, cause I don't have time to fix the translations. (All the translations explaining a command are wrong for sure cause they also translate the command)

**Comment by tastybento** [comment]
Thanks! If you use GitLocalize then you can create a PR directly from it.

**Pull request merged**
